import Line from '@/components/Line';
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Navbar from '../../components/Navbar'
import moment from 'moment/moment';
import { BiCart } from 'react-icons/bi';
import ProductLoading from '@/components/ProductLoading';
import { postRequest } from '@/Functions/Requests';
import { useRouter } from 'next/router';
import { getToken } from '@/Functions/getToken';
import { Logout } from '@/Functions/Logout';

export default function order() {
    const router = useRouter();
    const [data, setData] = useState({});

    const getOrder = async (id) => {
        try {
            const data = await postRequest('/api/orderDetail', { id: id })
            setData(data)
            console.log(data)
        } catch (error) {
            console.log('err')
        }
    }

    useEffect(() => {
        if (router.isReady) {
            const { id } = router.query;
            getOrder(id)
        }
    }, [router.isReady])

    useEffect(() => {
        if (!getToken()) {
            router.push(Logout());
        }
    }, [])


    return (
        <>
            <Head>
                <title>{data.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <main className='w-100 flex flex-col'>
                <Navbar />
                {data && data.id ?
                    <div className='w-full flex flex-col gap-2 px-2 md:px-4 pb-10 mt-20 md:mt-20'>
                        <div className='w-full grid gap-6 grid-cols-1 md:grid-cols-3'>
                            <div className='flex flex-col gap-4 overflow-scroll md:overflow-hidden w-full md:col-span-2'>
                                {data.products.map((e, i) => {
                                    return (
                                        <div  key={`thumbnail-${i}`} className='w-full flex-col md:flex-row shadow-lg p-2 flex gap-4'>
                                            <img className='w-full md:w-48' src={e.product.thumbnail} alt='' />
                                            <span>{e.product.title}</span>
                                        </div>
                                    )
                                })}

                            </div>
                        </div>
                    </div>
                    :
                    <div className='w-full flex flex-col gap-2 px-2 md:px-4 pb-10 mt-20 md:mt-20'>
                        <ProductLoading />
                    </div>
                }
            </main>
        </>
    )
}
