import Navbar from '../components/Navbar'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import LinesEllipsis from 'react-lines-ellipsis'
import responsiveHOC from 'react-lines-ellipsis/lib/responsiveHOC'
import { BiMinus, BiPlus } from 'react-icons/bi'

const ResponsiveEllipsis = responsiveHOC()(LinesEllipsis)


export default function Cart() {
    const [cart, setCart] = useState([])

    const getLocalStorage = () => {
        const localCart = JSON.parse(localStorage.getItem('cart')) || [];
        setCart(localCart)
    }

    useEffect(() => {
        getLocalStorage()    
    }, [])

    const AddQuantity = (item) => {
        const increaseItem = [...cart]
        const findIndex = increaseItem.findIndex((e) => e.id === item.id);
        increaseItem[findIndex].quantity++;
        localStorage.setItem('cart', JSON.stringify(increaseItem));
        getLocalStorage();
    }

    const MinusQuantity = (item) => {
        const increaseItem = [...cart]
        const findIndex = increaseItem.findIndex((e) => e.id === item.id);
        increaseItem[findIndex].quantity > 1 ? increaseItem[findIndex].quantity-- : 1;
        localStorage.setItem('cart', JSON.stringify(increaseItem));
        getLocalStorage();
    }

    return (
        <>
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <main className='w-full'>
                <Navbar cart={cart} />
                <main className='w-full flex flex-col md:flex-row box-border'>
                    <div className='mt-20 md:mt-16 px-2 md:px-16 pb-4 md:pb-10 w-full flex flex-col'>
                        <span className='text-xl uppercase font-semibold mb-4 text-red-500 mx-auto'>Cart</span>
                        {cart && cart.length > 0 &&
                            <div className='w-full grid gap-6 justify-start items-start grid-cols-1 md:grid-cols-3'>
                                <div className='md:col-span-2 justify-start items-start font-medium flex flex-col gap-4 p-2 border bottom-2 border-red-500'>
                                    {cart.map((item, i) => {
                                        return (
                                            <div key={`cart${i}`} className='w-full relative flex gap-4 flex-row'>
                                                <img alt={item.title} src={item.thumbnail} className='bg-cover w-24 md:w-44 h-24 md:h-44 bg-no-repeat' />
                                                <div className='flex flex-col mr-auto'>
                                                    <span className='font-medium '>{item.title}</span>
                                                    <span className='font-medium text-xs'>
                                                        <ResponsiveEllipsis
                                                            text={item.description}
                                                            maxLine='3'
                                                            ellipsis='...'
                                                            trimRight
                                                            basedOn='letters'
                                                        />
                                                    </span>
                                                    <div className='flex gap-4 mt-4 items-center'>
                                                        <button onClick={() => MinusQuantity(item)} className='p-2 bg-red-500 text-white'>
                                                            <BiMinus />
                                                        </button>
                                                        <span>{item.quantity}</span>
                                                        <button onClick={() => AddQuantity(item)} className='p-2 bg-red-500 text-white'>
                                                            <BiPlus />
                                                        </button>
                                                    </div>
                                                </div>
                                                <span className='font-semibold absolute left-0 px-2 py-1 bg-red-500 text-white z-10 text-sm'>&#x20b9; {item.price}</span>
                                            </div>
                                        )
                                    })}
                                </div>
                                <div className='md:col-span-1 justify-start h-auto items-start flex flex-col p-2 border bottom-2 border-red-500'>
                                    <span className='mb-2 text-lg font-semibold'>Summary</span>
                                    <div className='w-full font-medium flex flex-row justify-between items-center'>
                                        <span className='font-medium'>Product Price</span>
                                        <span className='font-semibold'>&#x20b9; 1542</span>
                                    </div>
                                    <div className='w-full font-medium flex flex-row justify-between items-center'>
                                        <span className='font-medium'>Shipping Charges</span>
                                        <span className='font-semibold'>&#x20b9; 1542</span>
                                    </div>
                                    <div className='w-full font-medium flex flex-row justify-between items-center'>
                                        <span className='font-medium'>Final Price</span>
                                        <span className='font-semibold'>&#x20b9; 1542</span>
                                    </div>
                                    <button className='w-full font-medium bg-red-500 py-2 mt-6 mb-1 text-white text-sm rounded'>Continue to Payment</button>
                                </div>
                            </div>
                        }
                    </div>
                </main>
            </main>
        </>
    )
}
