import Navbar from '../components/Navbar'
import Head from 'next/head'


export default function Login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <main className='w-100'>
                <Navbar />
            </main>
        </>
    )
}
